### ISSUE TITLE
TS3 Crash

### ISSUE THREAD

**Issue by rabid-1** [nimradium/ts3_channel_watcher#3]
**Describe the bug**
Whenever you are set up to follow and receive notifications for a channel if the channels name gets changed you will crash.

**Attatchment**
[ts3dump_1586731456878.zip](https://github.com/nimradium/ts3_channel_watcher/files/4467371/ts3dump_1586731456878.zip)

**To Reproduce (or what you did that caused the bug)**
1. use the plugin to watch any channel
2. Change the name of the channel on a different client
3. TeamSpeak will crash.

**Desktop (please complete the following information):**
 - OS: win64
 - Plugin Version latest
 - TS-Client Version 3.5.3? or 3.5.2

**Comment by nimradium** [comment]
Thank you for reporting this.
I'm going to have a look into this and I hope I can fix this in in a few days.

I'm happy to see that you continued using my Plugin 😄

**Comment by Hoodratss** [comment]
The plugin is great and works very well thank you very much. You should continue with it and add GUI and other various features you talked about.

**Comment by nimradium** [comment]
Thanks 😄
I've currently paused to work on it until Teamspek announces how they are going to handle Plugins in TS5 but I'm looking forward to add these features.

**Comment by nimradium** [comment]
I think I've fixed the problem, but I'll investigate further and plan on releasing a patch tomorrow.

**Comment by nimradium** [comment]
I've fixed the issue and released a [new version](https://github.com/nimradium/ts3_channel_watcher/releases/tag/v0.2.2.7-alpha).

I'm going to close this issue but feel free to reopen it if the bug somehow still exists or if there is anything else.
